# deploy.yml

name: Deploy to GitHub Pages

on:
  # Run this workflow every time you push to the `main` branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./barcelona-guide
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 18 # Use a recent LTS version of Node.js
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # 'ci' is faster and more reliable for CI/CD

      - name: Build your Astro site
        run: npm run build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
